name: dannybot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0  # Girişi hatırlama paketi

# DEV DEPENDENCIES (SADECE GELİŞTİRME İÇİN GEREKLİ)
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # <-- HATA VEREN PAKET BURADA

flutter:
  uses-material-design: true

  assets:
    - assets/

# İKON AYARLARI (GEÇEN SEFER EKLEDİĞİMİZ)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" # (Umarım assets/icon.png diye bir resmin vardır)
  adaptive_icon_background: "#111827"
  adaptive_icon_foreground: "assets/icon.png"